clean: true
author: bcylin
author_url: https://github.com/bcylin
github_url: https://github.com/bcylin/QuickTableViewController
github_file_prefix: https://github.com/bcylin/QuickTableViewController/blob/develop
xcodebuild_arguments: [-scheme, QuickTableViewController-iOS]
module: QuickTableViewController
module_version: 0.3.0
output: docs/output
theme: fullwidth
